In [1]:
#simple heat map

In [2]:
import os
import folium

print(folium.__version__)

0.7.0


In [5]:
import numpy as np

data = (
    np.random.normal(size=(100, 3)) *
    np.array([[1, 1, 1]]) +
    np.array([[48, 5, 1]])
).tolist()

print (data)

[[46.844764984392604, 5.622465253872864, 1.3744353607336453], [48.37034611067108, 3.8399996160719727, -0.9686360777378886], [46.662057955045945, 6.260977302134158, -1.0307743182802933], [48.34686288141354, 6.025663935434893, -0.806029529916436], [48.92138947867714, 6.9620540228699594, 0.3181174928217545], [45.75108840681891, 3.4489730432251395, 0.0012262746921701817], [46.59940447194297, 5.8328843905637475, 0.08660554822494804], [49.717182979202526, 4.839154283849482, 1.0930641902487785], [46.95651013189926, 5.306682910955781, 0.19396280520925258], [48.942660129963805, 3.9748550353696555, 0.5859099888305512], [47.489078226291916, 5.139442434860108, 1.2834126265235837], [47.11381778242949, 3.7434750623459885, 1.47310096349617], [47.97285274269129, 4.23526794609508, 0.10988221017473443], [48.07190437060391, 5.2578800938922585, 0.2925699895328352], [47.506154510308065, 5.730768706914361, 1.5947430009911692], [45.902944027220265, 5.570375345197377, 0.4109726884209951], [48.1629139055031, 5

In [4]:
from folium.plugins import HeatMap

m = folium.Map([48., 5.], tiles='stamentoner', zoom_start=6)

HeatMap(data).add_to(m)

m.save(os.path.join('./', 'Heatmap.html'))

m

In [7]:
datat = np.random.normal(size=(100, 3))

In [8]:
print (datat)

[[ 1.08399907  1.61779108  0.68180761]
 [-0.65052319  0.76559747  0.67506654]
 [-0.46363726  0.15204269  0.14999143]
 [ 1.30424044 -0.18572585  0.11133385]
 [-1.70351316  0.15725861 -0.32416939]
 [ 0.52285617 -0.75032843  0.38196763]
 [ 0.57282114  0.28648797 -0.57718795]
 [ 1.48132465  1.116061    0.43857826]
 [ 0.18180337  0.14052846 -0.17185032]
 [-0.10508794 -0.24362027  1.16097871]
 [-1.47713997 -0.07207209  0.26083433]
 [-0.96409656 -0.44799394 -0.41493026]
 [ 0.21924518  0.37451157 -0.38679069]
 [ 0.69859864  0.94185833  0.64504676]
 [ 0.10661213  1.06181022  0.06558298]
 [ 0.802719   -0.64560374 -2.2830071 ]
 [ 1.66618961 -0.12264597 -2.90843106]
 [ 1.58399245 -0.18034439  0.4264758 ]
 [-1.23315484 -1.85006142 -0.81621818]
 [ 0.72715159  0.5521757  -0.0462719 ]
 [ 1.4317569   0.77721238  1.71096427]
 [-0.3105563  -1.38672572  0.10414634]
 [ 0.00381406  0.0552332  -0.74155743]
 [-1.56461727  0.42913611  1.2213652 ]
 [-1.54042628  0.79974638 -3.01215437]
 [-0.91423316 -2.11303336

In [9]:
!ls


a1-LakeRumiraandGashora-rwanda.ipynb  a2-lake2.ipynb  simple heat map.ipynb
a2-blackImageDebug.ipynb	      Heatmap.html
